package com.lcjian.spunsugar.entity;

// Generated 2015-10-25 11:06:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * HentaiAnimeSeries generated by hbm2java
 */
public class HentaiAnimeSeries implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = 1L;
    @Expose
    private int id;
    @Expose
    private String name;
    @Expose
    private String overview;
    @Expose
    private Byte status;
    @Expose
    private String poster;
    private Set<HentaiAnimeEpisode> hentaiAnimeEpisodes = new HashSet<HentaiAnimeEpisode>(0);

    public HentaiAnimeSeries() {
    }

    public HentaiAnimeSeries(int id) {
        this.id = id;
    }

    public HentaiAnimeSeries(int id, String name, String overview, Byte status,
            String poster, Set<HentaiAnimeEpisode> hentaiAnimeEpisodes) {
        this.id = id;
        this.name = name;
        this.overview = overview;
        this.status = status;
        this.poster = poster;
        this.hentaiAnimeEpisodes = hentaiAnimeEpisodes;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getOverview() {
        return this.overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public String getPoster() {
        return this.poster;
    }

    public void setPoster(String poster) {
        this.poster = poster;
    }

    public Set<HentaiAnimeEpisode> getHentaiAnimeEpisodes() {
        return this.hentaiAnimeEpisodes;
    }

    public void setHentaiAnimeEpisodes(Set<HentaiAnimeEpisode> hentaiAnimeEpisodes) {
        this.hentaiAnimeEpisodes = hentaiAnimeEpisodes;
    }

}
