package com.lcjian.spunsugar.entity;

// Generated 2015-10-25 11:06:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * HentaiAnime generated by hbm2java
 */
public class HentaiAnimeGenre implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = 1L;
    @Expose
    private int id;
    @Expose
    private String name;
    @Expose
    private String type;
    private Set<HentaiAnimeEpisode> hentaiAnimeEpisodes = new HashSet<HentaiAnimeEpisode>(0);

    public HentaiAnimeGenre() {
    }

    public HentaiAnimeGenre(int id) {
        this.id = id;
    }

    public HentaiAnimeGenre(int id, String name, String type,
            Set<HentaiAnimeEpisode> hentaiAnimeEpisodes) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.hentaiAnimeEpisodes = hentaiAnimeEpisodes;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Set<HentaiAnimeEpisode> getHentaiAnimeEpisodes() {
        return this.hentaiAnimeEpisodes;
    }

    public void setHentaiAnimeEpisodes(Set<HentaiAnimeEpisode> hentaiAnimeEpisodes) {
        this.hentaiAnimeEpisodes = hentaiAnimeEpisodes;
    }

}
