package com.lcjian.spunsugar.entity;

// Generated 2015-10-25 11:06:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * HentaiAnimeMaker generated by hbm2java
 */
public class HentaiAnimeMaker implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = 1L;
    @Expose
    private int id;
    @Expose
    private String name;
    @Expose
    private String logo;
    @Expose
    private String description;
    private Set<HentaiAnimeEpisode> hentaiAnimeEpisodes = new HashSet<HentaiAnimeEpisode>(0);

    public HentaiAnimeMaker() {
    }

    public HentaiAnimeMaker(int id) {
        this.id = id;
    }

    public HentaiAnimeMaker(int id, String name, String logo,
            String description, Set<HentaiAnimeEpisode> hentaiAnimeEpisodes) {
        this.id = id;
        this.name = name;
        this.logo = logo;
        this.description = description;
        this.hentaiAnimeEpisodes = hentaiAnimeEpisodes;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<HentaiAnimeEpisode> getHentaiAnimeEpisodes() {
        return this.hentaiAnimeEpisodes;
    }

    public void setHentaiAnimeEpisodes(Set<HentaiAnimeEpisode> hentaiAnimeEpisodes) {
        this.hentaiAnimeEpisodes = hentaiAnimeEpisodes;
    }

}
