package com.lcjian.spunsugar.entity;

import com.google.gson.annotations.Expose;

// Generated 2016-1-15 21:54:05 by Hibernate Tools 4.0.0

/**
 * MovieVideo generated by hbm2java
 */
public class MovieVideo implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = 1L;
    @Expose
    private Integer id;
    private Movie movie;
    @Expose
    private String url;
    @Expose
    private String type;
    @Expose
    private String name;

    public MovieVideo() {
    }

    public MovieVideo(Movie movie, String url, String type) {
        this.movie = movie;
        this.url = url;
        this.type = type;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Movie getMovie() {
        return this.movie;
    }

    public void setMovie(Movie movie) {
        this.movie = movie;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
