package com.lcjian.spunsugar.entity;

import java.util.HashSet;
import java.util.Set;

// Generated 2016-1-15 21:54:05 by Hibernate Tools 4.0.0

/**
 * MovieGenre generated by hbm2java
 */
public class MovieGenre implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private String name;
    private Set<Movie> movies = new HashSet<Movie>(0);

    public MovieGenre() {
    }

    public MovieGenre(String name) {
        this.name = name;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<Movie> getMovies() {
        return movies;
    }

    public void setMovies(Set<Movie> movies) {
        this.movies = movies;
    }

}
