package com.lcjian.spunsugar.entity;

import com.google.gson.annotations.Expose;

// Generated 2015-10-11 18:29:14 by Hibernate Tools 4.0.0

/**
 * LiveSource generated by hbm2java
 */
public class TvLiveSource implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private TvStation tvStation;
    @Expose
    private String uri;
    @Expose
    private String type;

    public TvLiveSource() {
    }

    public TvLiveSource(TvStation tvStation) {
        this.tvStation = tvStation;
    }

    public TvLiveSource(TvStation tvStation, String uri, String type) {
        this.tvStation = tvStation;
        this.uri = uri;
        this.type = type;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public TvStation getTvStation() {
        return this.tvStation;
    }

    public void setTvStation(TvStation tvStation) {
        this.tvStation = tvStation;
    }

    public String getUri() {
        return this.uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
