package com.lcjian.spunsugar.entity;

// Generated 2015-10-11 18:29:14 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * TvStation generated by hbm2java
 */
public class TvStation implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = 1L;
    @Expose
    private Integer id;
    @Expose
    private String name;
    @Expose
    private String logo;
    @Expose
    private String type;
    @Expose
    private String channel;
    private Set<TvLiveSource> tvLiveSources = new HashSet<TvLiveSource>(0);
    @Expose
    private Program now;
    @Expose
    private Program next;
    
    public TvStation() {
    }

    public TvStation(String name) {
        this.name = name;
    }

    public TvStation(String name, String logo, String type,
            Set<TvLiveSource> tvLiveSources) {
        this.name = name;
        this.logo = logo;
        this.type = type;
        this.tvLiveSources = tvLiveSources;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Set<TvLiveSource> getTvLiveSources() {
        return this.tvLiveSources;
    }

    public void setTvLiveSources(Set<TvLiveSource> tvLiveSources) {
        this.tvLiveSources = tvLiveSources;
    }

    public Program getNow() {
        return now;
    }

    public void setNow(Program now) {
        this.now = now;
    }

    public Program getNext() {
        return next;
    }

    public void setNext(Program next) {
        this.next = next;
    }

    public String getChannel() {
        return channel;
    }

    public void setChannel(String channel) {
        this.channel = channel;
    }
}
